### ISSUE TITLE
Publish хост приложения и всех плагинов "скриптом" (для деплоя)

### ISSUE THREAD

**Issue by VladSnap** [boolqa/rapid#12]
- Нужно сделать аналогично как при сборке для отладки, чтобы собиралось все в одну выходную директорию, только при паблише. Так мы сможем быстро тестировать и не делать лишних ручных действий при паблише.
- Предложить варианты решения проблемы. (Возможно придется написать скрипт сборки)
- Возможно стоит сразу сделать все для докера, а не отдельно при паблише из под студии.

**Comment by SergeyRonzhin** [comment]
Сделано в рамках issue https://github.com/boolqa/rapid/issues/15.
Этот issue закрываю.
