### ISSUE TITLE
Внедрить Docker

### ISSUE THREAD

**Issue by VladSnap** [boolqa/rapid#15]
* Приложение и все его зависимости должны разворачиваться в докере.
* Нужно заполнить докер файл.
* Проверить работоспособность образа докера.

**Comment by SergeyRonzhin** [comment]
Изменил Dockerfile из коробки таким образом, чтобы:
- приложение и его зависимости собирались и публиковались в `Release` режиме
- каждый проект плагина делали тоже самое
- всё это делалось параллельно дабы ускорить формирование образа
- копировалась папка `src` с исходниками в контейнер для `development` окружения, чтобы была возможность проводить `debug` в контейнере

Проверил работоспособность:
- через `debug` в студии через профиль `Docker` (см. `launchsettings.json`)
- через создание образа и контейнера вручную
